### ISSUE TITLE
New, different view (version B)

### ISSUE THREAD

**Issue by RicsiToth** [bacigala/wtam-project#6]
- [x] "heureka" style view

**Comment by bacigala** [comment]
Version B was created as 2 components - Calendar and EventDetailsPopup, they are not visible by default in the production version of the app, however can be accessed by appending/inserting "B" to the url on calendar pages

### How to access version B:
 - **mycalendar page** append `B` to url, instead of https://cinkaren.herokuapp.com/mycalendar, use https://cinkaren.herokuapp.com/mycalendarB
 - **gym calendar** when viewing calendar for specific gym, append `B` to "calendar" substring in the url, e.g. use https://cinkaren.herokuapp.com/calendarB/1 for version B of https://cinkaren.herokuapp.com/calendar/1
